; LIMITED EBCDIC TO ASCII
; CODE CONVERSION PROGRAM

DATA SEGMENT
EBCDIC DB 0F0H,0F2H,0F2H,0F3H,0F4H,0F5H
       DB 0F6H, 0F7H,0F8H,0F9H
       DB 0C1H,0C2H,0C3H,0C4H,0C5H,0C6H
       DB 0C7H,0C8H,0C9H
       DB 0D1H,0D2H,0D3H,0D4H,0D5H,0D6H
       DB 0D7H,0D8H,0D9H
       DB 0E2H,0E3H,0E4H,0E5H,0E6H,0E7H
       DB 0E8H,0E9H
       
ASCII  DB '0123456789'
       DB 'ABCDEFGHI'
       DB 'JKLMNOPQR'
       DB 'STUVWXYZ'
       
       DATA ENDS
       CODE SEGMENT
       ASSUME DS:DATA,CS:CODE
       
CONVERT: MOV AX,DATA  ; MOVE DATA TO AX
         MOV DS,AX    ; MOVE AX TO DATA SEGMENT  
         MOV CX,24H   ; MOVE 24H TO CX   
         XOR AX,AX    ; CLEAR AX REGISTER  
      
         LEA SI, ASCII ; LOAD ASCII DATA TO SI MEMEORY LOCATION 
         LEA DI,EBCDIC ; LOAD EBCDIC TO DI MEMORY LOCATION 
         MOV AL,00F3H  ; MOVE 0F3H TO AL  
LOOPING: CMP AL,[DI]   ; COMPARE DI MEMORY TO AL  
         JE EQUAL      ; IF THEY ARE EQUAL JUMP ON LINE 38 
         INC SI        ; INCREMENT SI 
         INC DI        ; INCREMENT DI 
         DEC CX        ; DECREMENT CX 
         JNZ LOOPING   ; JUMP BACK TO LINE31 IF CX IS NOT ZERO 
         
   EQUAL:MOV BL,DS[SI] ; MOVE MEMORY TO BL REGISTER
         HLT   
         CODE ENDS
         END CONVERT
       
               