;STEEVE BISSERETH
;LIMITED EBCDIC TO ASCII
;CODE CONVERSION PROGRAM
;   EBCDIC IN AL;
;  ASCII RETURNED IN BL.
;   USES TABLE LOOKUP.
; USES SI AND DI AS POINTERS.
;RETURNS 0 FOR AN INVALID INPUT CODE.

DATA SEGMENT
    EBCDIC  DB 0F0H,0F1H,0F2H,0F3H,0F4H,0F5H
            DB 0F6H,0F7H,0F8H,0F9H
            DB 0C1H,0C2H,0C3H,0C4H,0C5H,0C6H
	    DB 0C7H,0C8H,0C9H
	    DB 0D1H,0D2H,0D3H,0D4H,0D5H,0D6H
	    DB 0D7H,0D8H,0D9H
	    DB 0E2H,0E3H,0E4H,0E5H,0E6H,0E7H
	    DB 0E8H,0E9H

    ASCII   DB '0123456789'

	    DB 'ABCDEFGHI'

	    DB 'JKLMNOPQR'

	    DB 'STUVWXYZ'

DATA ENDS

CODE SEGMENT

      ASSUME DS:DATA,CS:CODE

CONVERT:MOV DX,DATA
        MOV DS,DX

        LEA SI,EBCDIC
        LEA DI,ASCII
        MOV CL,36
        
AGAIN:  CMP AL,[SI]
        JE DONE
        INC SI
        DEC CL
        JNZ AGAIN
        MOV BL,0
        JMP FINISH
        
DONE:   ADD DI,SI
        MOV BL,[DI]
FINISH: RET

CODE ENDS
END CONVERT
