;STEEVE BISSERETH
;16 BIT FACTORIAL X SUBROUTINE
;WHERE X IS IN THE CX REGISTER
;ANSWER RETURNED IN AX
;X <= 8; 8! = 9D80H = 40,320

CODE SEGMENT

    ASSUME CS:CODE
    
FACTORIAL: MOV AX,01H
           CMP CX,00H
           JCXZ EXIT

AGAIN:     MUL CX
           DEC CX
           JNZ AGAIN

EXIT:      RET

CODE ENDS
END FACTORIAL